### PR TITLE
DVCI-185: Submit Health Event Compliance Tests

### PR DESCRIPTION
**Pull request by mickohanlon23**
Pull Request for [DVCI-185: Test Feature - Submit health event to DDCC Certificate Generation Service](https://jira.mitre.org/browse/DVCI-185).

Creates Gherkin test scenarios and accompanying Cucumber mock unit tests for [Submit Health Event](https://worldhealthorganization.github.io/ddcc/transactions.html#submit-health-event) and [Generate Health Certificate](https://worldhealthorganization.github.io/ddcc/OperationDefinition-DDCC-QuestionnaireResponse-generateHealthCertificate.html). Documentation for testing decisions can be found on the [DDCC Compliance Testing Confluence page](https://confluence.mitre.org/display/DVCI/DDCC+Compliance+Testing). 

_Note: Review https://github.com/dvci/ddcc-compliance-testing-framework/pull/2 first as this pull request includes changes made there._

### CODE REVIEW

**Review by sarahmcdougall — APPROVED** [review]
I'm not really seeing any changes that should be made (the tests all pass, I think the mock config pactum matchers are specific enough, etc.). Definitely worth getting someone else to take a look at this before merging - I've been working with the compliance framework a lot so I may have overlooked something.

I think it may be worth further organizing all the fixtures under the `features` directory. I am bringing in more files for my work and so I made subdirectories for each feature. I found it helpful to have it more organized because some of the file names aren't that intuitive.

**Comment by mickohanlon23** [comment]
> I'm not really seeing any changes that should be made (the tests all pass, I think the mock config pactum matchers are specific enough, etc.). Definitely worth getting someone else to take a look at this before merging - I've been working with the compliance framework a lot so I may have overlooked something.
> 
> I think it may be worth further organizing all the fixtures under the `features` directory. I am bringing in more files for my work and so I made subdirectories for each feature. I found it helpful to have it more organized because some of the file names aren't that intuitive.

@sarahmcdougall Good idea. My most recent commit organizes `features/fixtures` into two separate subdirectories, each corresponding with one of the test features.

**Review by pmadria — APPROVED** [review]
Looks good...All the tests pass and the Bundle is matching the framework. 

One thing to add would be to potentially update the `README.md` because right now it says it's optional to run the docker command but it is necessary to pass all the tests.

**Comment by mickohanlon23** [comment]
> 

We had a similar conversation about this on @nkarip's pull request here: https://github.com/dvci/ddcc-compliance-testing-framework/pull/2#discussion_r756302217.

As a result we added the `.env.test` file, and instructions under the "[Run Cucumber unit tests locally using mock server](https://github.com/dvci/ddcc-compliance-testing-framework#run-cucumber-unit-tests-locally-using-mock-server)" section in the README explaining that the VALIDATOR_SERVICE_URL environment variable should be removed if you don't have access to the validator service. I think that clears up confusion with the optional comment, but let me know if you think things should be clarified further.

**Comment by mickohanlon23** [comment]
> Looks good...All the tests pass and the Bundle is matching the framework.
> 
> One thing to add would be to potentially update the `README.md` because right now it says it's optional to run the docker command but it is necessary to pass all the tests.

We had a similar conversation about this on @nkarip's pull request here: #2 (comment).

As a result we added the .env.test file, and instructions under the "Run Cucumber unit tests locally using mock server" section in the README explaining that the VALIDATOR_SERVICE_URL environment variable should be removed if you don't have access to the validator service. I think that clears up confusion with the optional comment, but let me know if you think things should be clarified further.

**Pull request merged**
